config/routes.rb
require_relative '../app/middleware/walletonemdw.rb'
Rails.application.routes.draw do
  root 'products#index'
  mount WM => '/w1_callback'
  devise_for :admins
  devise_for :users

  resources :categories
  resources :products do
    resources :comments
  end
  get 'products/:id/similar' => 'products#similar', as: :similar_product
  get 'admin_panel/categories' => 'admin_panel#categories', as: :admin_categories
  get 'admin_panel/products' => 'admin_panel#products', as: :admin_products
  get '/cart' => 'cart#index', as: :cart
  get 'cart/update' => 'cart#update', as: :cart_update
  get 'cart/clear' => 'cart#clear'
  get 'cart/:id' => 'cart#add', as: :cart_add
  get '/admin_panel' => 'admin_panel#index', as: :admin_root
  get 'page/about'
  get 'page/contact'
  post '/payorder' => 'orders#create', as: :pay_order
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id = params[:id]
    session[:cart] = {} unless session[:cart]
    cart = session[:cart]
    cart[id] = if cart[id]
                 cart[id] + 1
               else
                 1
               end
    redirect_to action: :index
  end
  def update
    p params
    id = params[:id]
    quantity = params[:quantity]  
    session[:cart][id] = params[:quantity].to_i
    respond_to do |format|
      format.html  { redirect_to action: :index }
    end
  #  redirect_to action: :index
  end
  def clear
    if !params[:id]
      session[:cart] = nil
      redirect_to action: :index
    else
      session[:cart].delete(params[:id])
      redirect_to action: :index
    end
  end

  def index
    @cart = if session[:cart]
              session[:cart]
            else
              {}
            end
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/index.html.erb
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<%= stylesheet_link_tag params[:controller] %>
<table id="cart" class="table table-hover table-condensed">
    <thead>
        <tr>
            <th style="width:50%">Товар</th>
            <th style="width:10%">Цена</th>
            <th style="width:8%">Количество</th>
            <th style="width:22%" class="text-center">Итог</th>
            <th style="width:10%"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <% total = 0 %>
            <% if @cart.empty? %>
            <td data-th="Product">
                <div class="row">
                    <div class="col-sm-5 hidden-xs" style="margin-top: 10px">
                        <p>Корзина пуста</p>
                    </div>
                </div>
                <td>
                    <%end%>
                    <% @cart.each do |id, quantity| %>
                    <% product = Product.find_by_id(id) %>
                    <td data-th="Product">
                        <div class="row">
                            <%= link_to product_path(product) do %>
                            <div class="col-sm-2 hidden-xs">
                                <%= image_tag product.images.first.link, class: 'img-responsive' %>
                            </div>
                            <div class="col-sm-10">
                                <h4 class="nomargin"><%= product.title %></h4>
                            </div>
                            <%end%>
                        </div>
                    </td>
                    <td data-th="Price">$<%= product.price %></td>
                    <td data-th="Quantity">
                        <%= form_tag cart_update_path, method: :get, action: :update, id: "form#{id}" do %>
                        <%= hidden_field_tag :id, product.id, id: 'p_id' %>
                        <%= number_field_tag :quantity, quantity, in: 1..100, class: 'form-control text-center', id: id.to_s, onchange: 'changePrice(this.id, this.value)' %>
                        <%end%>
                    </td>
                    <td data-th="Subtotal" id=<%="sub#{id}"%> name=<%="#{product.price}"%> class="text-center">$<%= product.price * quantity %></td>
                    <td class="actions">
                        <% total += product.price * quantity %>
                        <%= link_to '#' do%>
                        <%end%>
                        <%= link_to cart_clear_path(id: product.id), style: 'margin-left: 80px;' do%>
                        <button class="btn btn-danger btn-sm">
                            <i class="fa fa-trash-o"></i>
                        </button>
                        <%end%>
                    </td>
                </tr>
                <%end%>
            </tbody>
            <tfoot>
                <tr class="visible-xs">
                    <td class="text-center">
                        <strong>Total $<%= "#{total}" %></strong>
                    </td>
                </tr>
                <tr>
                    <td><%= link_to root_path, class: 'btn btn-warning' do%>
                        <i class="fa fa-angle-left"></i>
                        Продолжить покупки<%end%></td>
                    <td colspan="2" class="hidden-xs"></td>
                    <td class="hidden-xs text-center">
                        <strong>Итог $<span id="total-price"><%= "#{total}" %></span>
                        </strong>
                    </td>
                    <td>
                        <%= button_tag 'Оплатить', onclick: 'checkout(this)',
                        id: 'paySubmitBtn', 'data-toggle': 'popover', 'data-placement': 'bottom',
                         'data-content': 'Сначала добавьте товары', 'data-animation': 'true',
                          class: 'btn btn-success btn-block' %>
                    </td>
                </tr>
            </tfoot>
        </table>
        <div style="margin: auto">
            <%= form_tag pay_order_path, method: :post, id: 'payForm' do %>
            <div class="form-group">
                <%= label_tag :name, 'Имя' %>
                <%= text_field_tag :name, nil, class: 'form-control', required: true %>
            </div>
            <div class="form-group">
                <%= label_tag :email %>
                <%= email_field_tag :email, nil, class: 'form-control', required: true %>
            </div>
            <div class="form-group">
                <%= label_tag :tel, 'Телефон' %>
                <%= telephone_field_tag :tel, nil, class: 'form-control', required: true %>
            </div>
            <div class="form-group">
                <%= label_tag :'Город' %>
                <%= text_field_tag :city, nil, class: 'form-control', required: true %>
            </div>
            <div class="form-group">
                <%= label_tag :'Отделение новой почты' %>
                <%= number_field_tag :office, nil, class: 'form-control', min: 1, required: true %>
            </div>
            <%= button_tag 'Оплатить', class: 'btn btn-success', id: 'submitBtn' %>
            <%end%>
        </div>