config/routes.rb
require_relative '../app/middleware/walletonemdw.rb'
Rails.application.routes.draw do
  root 'products#index'
  mount WM => '/w1_callback'
  devise_for :admins
  devise_for :users

  resources :categories
  resources :products do
    resources :comments
  end
  get 'products/:id/similar' => 'products#similar', as: :similar_product
  get 'admin_panel/categories' => 'admin_panel#categories', as: :admin_categories
  get 'admin_panel/products' => 'admin_panel#products', as: :admin_products
  get '/cart' => 'cart#index', as: :cart
  get 'cart/update' => 'cart#update', as: :cart_update
  get 'cart/clear' => 'cart#clear'
  get 'cart/:id' => 'cart#add', as: :cart_add
  get '/admin_panel' => 'admin_panel#index', as: :admin_root
  get 'page/about'
  get 'page/contact'
  post '/payorder' => 'orders#create', as: :pay_order
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController
  before_action :authenticate_admin!
  def index; end

  def products
    @products = Product.all
  end
  
  def categories
    @categories = Category.all
  end
end

app/views/admin_panel/_vmenu.html.erb
<%= stylesheet_link_tag 'admin_panel' %>
<div class="side-menu" style="margin-top: -30px;">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->

        <div class="navbar-header">
            <%= link_to admin_root_path do %>
            <div class="brand-wrapper">
                <div class="brand-name-wrapper">
                    <div class="navbar-brand">Admin</div>
                </div>
            </div>
            <%end%>
        </div>

        <div class="side-menu-container">
            <ul class="nav navbar-nav">
                <li><%= link_to 'Products', admin_products_path %></li>
                <li><%= link_to 'Categories', admin_categories_path %></li>
                <li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>
            </ul>
        </div>
    </nav>
</div>

app/views/admin_panel/categories.html.erb
<%= stylesheet_link_tag 'admin_panel' %>
<div class="row"><div class="col-sm-4" <%= render 'admin_panel/vmenu' %> </div> <div class="col-sm-8"> <%= link_to new_category_path do %> <button class="btn btn-success"> category</button> <%end%> <table class="table table-condensed"> <thead> <tr> <td>New Title</td>
<td>Edit</td>
<td>Delete</td>
</tr>
</thead>
<tbody>
<% @categories.each do |f| %>
<tr>
<td><%= link_to f.title, category_path(f) %></td>
<td><%= link_to 'edit', edit_category_path(f) %></td>
<td><%= link_to 'delete', category_path(f), method: :delete %></td>
<tr>
    <%end%>
</tbody>
</table>
</div>
<div>

app/views/admin_panel/index.html.erb
<div class="row">
    <div class="col-sm-4">
        <%= render 'vmenu' %>
    </div>
</div>

app/views/admin_panel/products.html.erb
<div class="row">
    <div class="col-sm-4">
        <%= render '/admin_panel/vmenu' %>
    </div>
    <div class="col-sm-8">
        <%= link_to new_product_path do %>
        <button class="btn btn-success">New product</button>
        <%end%>
        <table class='table table-condensed'>
            <thead>
                <tr>
                    <td>Category</td>
                    <td>Product Group</td>
                    <td>Title</td>
                    <td>Price</td>
                    <td>Show</td>
                    <td>Edit</td>
                    <td>Delete</td>
                </tr>
            </thead>
            <tbody>
                <% @products.each do |f| %>
                <tr>
                    <td>
                        <%= f.product_group.category.title %>
                    </td>
                    <td>
                        <%= f.product_group.id %>
                    </td>
                    <td>
                        <%= f.title %>
                    </td>
                    <td>
                        <%= f.price %>
                    </td>
                    <td>
                        <%= link_to 'show', product_path(f) %>
                    </td>
                    <td>
                        <%= link_to 'create_similar', similar_product_path(f) %>
                    </td>
                    <td>
                        <%= link_to 'edit', edit_product_path(f) %>
                    </td>
                    <td>
                        <%= link_to 'delete', f, method: :delete %>
                    </td>
                </tr>
                <%end%>
            </tbody>
        </table>
    </div>
</div>