config/routes.rb
require_relative '../app/middleware/walletonemdw.rb'
Rails.application.routes.draw do
  root 'products#index'
  mount WM => '/w1_callback'
  devise_for :admins
  devise_for :users

  resources :categories
  resources :products do
    resources :comments
  end
  get 'products/:id/similar' => 'products#similar', as: :similar_product
  get 'admin_panel/categories' => 'admin_panel#categories', as: :admin_categories
  get 'admin_panel/products' => 'admin_panel#products', as: :admin_products
  get '/cart' => 'cart#index', as: :cart
  get 'cart/update' => 'cart#update', as: :cart_update
  get 'cart/clear' => 'cart#clear'
  get 'cart/:id' => 'cart#add', as: :cart_add
  get '/admin_panel' => 'admin_panel#index', as: :admin_root
  get 'page/about'
  get 'page/contact'
  post '/payorder' => 'orders#create', as: :pay_order
end

app/models/product.rb
class Product < ApplicationRecord
  attr_accessor :images_links, :category_type, :property_data, :group
  belongs_to :product_group
  belongs_to :category
  has_many :images, dependent: :destroy, autosave: true
  has_many :comments, dependent: :destroy
  has_many :properties,dependent: :destroy, autosave: true
  validates_associated :images, :properties
  validates :title, presence: true, length: { in: 2..100 }
  validates :description, presence: true, length: { minimum: 2 }
  validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
#  before_action :authenticate_admin!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy, :similar]
  protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token
  def index
    @products = Product.all
  end

  def show; end

  def new
    @product = Product.new
  end

  def edit; end

  def similar
    @product = @product.dup
  end

  def create
    Product.transaction do
      category = Category.find_by_title(product_params[:category_type])
      if product_params[:group].to_i == 0
        @product_group = category.product_groups.create
      else
        @product_group = ProductGroup.find(product_params[:group].to_i)
      end
      property_data = product_params[:property_data].split
      @product = @product_group.products.new(product_params)
      property_data.each_slice(3) do |x|
        if x[2] == 'current'
          @product.properties.new(name: x[0], title: x[1], value: Product.last.id + 1)
        else
          @product.properties.new(name: x[0], title: x[1], value: x[2])
        end
      end
      product_params[:images_links].split('|').each do |x|
        @product.images.new(link: x)
      end
      respond_to do |format|
        if @product.save
          format.html { redirect_to admin_products_path }
        else
          flash[:notice] = @product.errors.messages.to_s
          format.html { render :new }
        end
      end
    end
  end

  def update
    Product.transaction do
      new_category = Category.find_by_title(product_params[:category_type])
      @product.product_group.category = new_category
      if product_params[:group].to_i == 0
        @product.product_group = new_category.product_groups.create
      else
        @product.product_group = ProductGroup.find(product_params[:group].to_i)
      end
      @product.properties.destroy_all
      property_data = product_params[:property_data].split
      property_data.each_slice(3) do |x|
        if x[2] == 'current'
          @product.properties.new(name: x[0], title: x[1], value: @product.id)
        else
          @product.properties.new(name: x[0], title: x[1], value: x[2])
        end
      end
      @product.images.destroy_all
      product_params[:images_links].split(/[\r\n]+/).each do |x|
        @product.images.new(link: x)
      end
      respond_to do |format|
        if @product.update(product_params)
          format.html { redirect_to admin_products_path }
        else
          flash[:alert] = @product.errors.messages.to_s
          format.html { render :edit }
        end
      end
    end
  end

  def destroy
    if @product.product_group.products.count == 1
      product_group = @product.product_group
      @product.destroy
      product_group.destroy
    else
      @product.destroy
    end
    respond_to do |format|
      format.html do
        redirect_to admin_products_path,
                    notice: 'Product was successfully destroyed.'
      end
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
    @product.images_links = ''.tap { |x|
      @product.images.each do |y|
        x << y.link + "\n"
      end
    }
    @product.category_type = @product.product_group.category.title
    @product.property_data = ''.tap { |x|
      @product.properties.each do |y|
        x << "#{y.name} #{y.title} #{y.value}" + "\n"
      end
    }
    @product.group = @product.product_group.id
  end

  def product_params
    params.require(:product).permit(:title,
                                    :description,
                                    :price,
                                    :category_type,
                                    :subcategory,
                                    :spec,
                                    :show_case,
                                    :images_links,
                                    :property_data,
                                    :group)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_comment.html.erb
<%= simple_form_for([@product, @product.comments.build]) do |f| %>
<p>
    <%= f.input :body, label: false, placeholder: 'Create comment' %>
</p>
<p>
    <%= f.submit %>
</p>
<%end%>
</p>

app/views/products/_comments.html.erb
<strong class="comments-title">Comments</strong>
<% @product.comments.each do |comment| %>
<p class="comenter-name"><%= comment.commenter[0, comment.commenter.index('@')] %>
    &#8226;
    <%= comment.created_at.to_formatted_s(:short) %></p>
<p class="comment-body"><%= comment.body %></p>
<%end%>

app/views/products/_form.html.erb
<p class="alert">
    <% @product.errors.full_messages.each do |msg| %>
    <%= "#{msg};" %>
    <% end %>
</p>
<%= simple_form_for @product do |f| %>
<%= f.input :title, autofocus: true %>
<%= f.input :description, input_html: {rows: 6} %>
<%= f.input :spec, as: :text, label: 'Specifications', input_html: {style: 'resize: none', rows: 6} %>
<%= f.input :show_case, as: :text, label: 'Show case', input_html: {style: 'resize: none', rows: 6} %>
<%= f.input :price, hint: 'Only numbers', input_html: {min: 0, step: 'any'} %>
<%= f.input :category_type, collection: Category.all.map(&:title), include_blank: false %>
<%= f.input :images_links, as: :text, input_html: {style: 'resize: none', rows: 5} %>
<%= f.input :property_data, as: :text, hint: 'name title value', input_html: {style: 'resize: none', rows: 5} %>
<%= f.input :group, hint: 'id integer only, or empty for create new group' %>
<%= f.input :subcategory %>
<%= f.button :submit, class: 'btn btn-success' %>
<%end%>

app/views/products/_main_slider.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <%= image_tag 'main_slider/og.png', class: 'first-slide slider-img', alt: 'First slide'%>
            <div class="container">
                <div class="carousel-caption">
                    <h1>
                        iPhone 7</h1>
                    <p>В iPhone 7 все важнейшие аспекты iPhone значительно улучшены. Это принципиально новая система камер для фото- и видеосъёмки.</p>
                    <p><%= link_to 'Купить', 'products/2', class: 'btn btn-lg btn-primary', role: 'button' %></p>

                </div>
            </div>
        </div>
        <div class="item">
            <%= image_tag 'main_slider/macbooki.jpg', class: 'second-slide slider-img', alt: 'Second slide'%>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Macbook</h1>
                    <p>Он стал ещё быстрее и мощнее. Легче и тоньше. У него самый яркий экран и лучшая цветопередача среди всех ноутбуков Mac.
                    </p>
                    <p><%= link_to 'Купить', 'products/5', class: 'btn btn-lg btn-primary', role: 'button' %></p>
                </div>
            </div>
        </div>
        <div class="item slider-img">
            <%= image_tag 'main_slider/watch.png', class: 'third-slide slider-img', alt: 'Third slide'%>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Watch</h1>
                    <p>Встроенный GPS‑модуль. Водонепроницаемость на глубине до 50 метров.1 Новый невероятно быстрый двухъядерный процессор. И в два раза более яркий дисплей.</p>
                    <p><%= link_to 'Купить', 'products/3', class: 'btn btn-lg btn-primary', role: 'button' %></p>
                </div>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

app/views/products/edit.html.erb
<div class="row">
    <div class="col-sm-4">
        <%= render '/admin_panel/vmenu' %>
    </div>
    <div class="col-sm-8">
        <h1 class="text-center">Editing product</h1>
        <%= render 'form', product: @product %>
    </div>
</div>

app/views/products/index.html.erb
<%= stylesheet_link_tag params[:controller] %>
<%= stylesheet_link_tag    'carousel.css', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'carousel.js', 'data-turbolinks-track': 'reload'%>
<%= render 'main_slider' %>

<% Product.all.each_with_index do |product, i| %>
<%if (i%4 == 0) %>
<div class="row">
    <%end%>
    <div class="col-sm-3 product-box">
        <%= link_to product do %>
        <%= image_tag(product.images.first.link, class: 'product_images_links') if (!product.images.first.nil?) %><br>
        <div style="height: 20px">
            <%= "#{product.title}" %>
        </div>
        <%end%><br>

        <%= link_to cart_add_path(product), class: 'link-pos' do %>
        <button type="button" class="btn btn-success add-cart-btn" style="text-decoration: none"><%= image_tag 'Add_to_Cart-512.png', class: 'cart-ico'%>
        </button>
        <%end%>
        <span class="price"><%= " $#{product.price}" %></span>

    </div>
    <%if (i%4 == 3) %>
</div>
<% end %>
<% end %>
<br>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>
    window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
</script>

app/views/products/new.html.erb
<div class="row">
    <div class="col-sm-4">
        <%= render '/admin_panel/vmenu' %>
    </div>
    <div class="col-sm-8">
        <h1 class="text-center">New product</h1>
        <%= render 'form', product: @product %>
    </div>
</div>

app/views/products/show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<%= stylesheet_link_tag 'products' %>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
<%= stylesheet_link_tag 'products_show' %>
<%= stylesheet_link_tag 'menu' %>
<div class="card">
    <div class="container-fliud">
        <div class="wrapper row">
            <div class="preview col-md-6">
                <div class="preview-pic tab-content">
                    <% @product.images.each_with_index do |f, i| %>
                    <div class="tab-pane<%if i == 0%> active<%end%>" id=<%="pic-#{i+1}"%>>
                        <%= image_tag f.link, class: 'slider-image' %>
                    </div>
                    <%end%>
                </div>
                <ul class="preview-thumbnail nav nav-tabs">
                    <% @product.images.each_with_index do |f, i| %>
                    <% if i == 0 %>
                    <li class="active" style=" width: <%= 90.0/@product.images.count %>%;margin-right: <%= 10.0/@product.images.count %>%">
                        <%else%>
                    <li style=" width: <%= 90.0/@product.images.count %>%;margin-right: <%= 10.0/@product.images.count %>%">
                        <%end%>
                        <%= link_to '#', 'data-target': "#pic-#{i+1}", 'data-toggle': 'tab' do %>
                        <%= image_tag f.link  %>
                        <%end%>
                    </li>
                    <%end%>
                </ul>
            </div>
            <div class="details col-md-6">
                <h3 class="product-title"><%= @product.title %></h3>
                <div class="rating">
                    <span class="review-no">41 reviews</span>
                </div>
                <% if @product.properties.where(name: 'color').any? %>
                <div class="colors">
                    <div class="row">
                        <div class="col-sm-2 col-md-2 mt-5">
                            <span>colors:</span>
                        </div>
                        <div class="col-sm-10 col-md-10">
                            <% @product.product_group.properties.where(name: 'color').to_a.uniq(&:title).each do |f| %>
                            <% if f.title == @product.properties.where(name: 'color').take.title %>
                            <%= link_to product_path(f.value.to_i), class: 'c-active', style: 'background:'+"#{f.title}"  do %>
                            <%end%>
                            <%elsif @product.product_group.find_product(properties: @product.properties, element: f) != -1 %>
                            <%= link_to product_path(@product.product_group.find_product(properties: @product.properties, element: f)), class: 'color', style: 'background:'+"#{f.title}" do %>
                            <%end%>
                            <%end%>
                            <%end%>
                        </div>
                    </div>
                    <%end%>
                    <% if @product.product_group.properties.where.not(name: 'color').any? %>
                    <% @product.product_group.properties.where.not(name: 'color').to_a.uniq(&:name).each do |f| %>
                    <div class="row">
                        <div class="col-sm-2 mt-5">
                            <%= f.name %>:
                        </div>
                        <div class="col-sm-10">
                            <% @product.product_group.properties.where(name: f.name).to_a.uniq(&:title).each do |x| %>
                            <% if x.title == @product.properties.where(name: x.name).take.title %>
                            <%= link_to product_path(x.value.to_i), class: 'proper-box-active' do %>
                            <span data-toggle="tooltip" title="<%= x.title %>"><%= x.title %></span>
                            <%end%>
                            <%elsif @product.product_group.find_product(properties: @product.properties, element: x) != -1  %>
                            <%= link_to product_path(@product.product_group.find_product(properties: @product.properties, element: x)), class: 'proper-box' do %>
                            <span class="size" data-toggle="tooltip" title="<%= x.title %>"><%= x.title %></span>
                            <%end%>
                            <%end%>
                            <%end%>
                        </div>
                    </div>
                    <%end%>
                    <%end%>
                    <div class="row">
                        <p class="product-description"><%= @product.description %></p>
                        <div class="row">
                            <div class="col-md-4">
                                <p class="price">Цена:
                                    <span>$<%= @product.price %>
                                        <span></p>
                                    </div>
                                    <div class="col-md-8">
                                        <%= link_to cart_add_path(@product) do %>
                                        <button type="button" class="btn btn-success add-cart-btn" style="text-decoration: none"><%= image_tag 'Add_to_Cart-512.png', class: 'cart-ico'%>
                                            Купить
                                        </button>
                                        <%end%>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <nav id="navigation">
                    <ul id="main-menu">
                        <li onclick="showFront()" class="current-menu-item" id="frontB">
                            <span>Витрина</span>
                        </li>
                        <li onclick="showProper()" id="propB">
                            <span>Характеристики</span>
                        </li>
                        <li onclick="showComments()" id="commentB">
                            <span>Отзывы</span>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12" id="front">
                <%=raw @product.show_case %>
            </div>
            <div class="col-md-12" id="proper" style="display: none">
                <%=raw @product.spec %>
            </div>
            <div class="col-md-12" id="commet" style="display: none">
                <div class="col-md-6 comments-title">
                    <%= render 'comments' %>
                    <% if user_signed_in? %>
                    <%= render 'add_comment' %>
                    <%end%>
                </div>
            </div>
        </div>
    </div>

app/views/products/similar.html.erb
<div class="row">
    <div class="col-sm-4">
        <%= render '/admin_panel/vmenu' %>
    </div>
    <div class="col-sm-8">
        <h1 class="text-center">Similar product</h1>
        <%= render 'form', product: @product %>
    </div>
</div>